create table if not exists public.programs (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    title text not null,
    tab_label text not null,
    language text not null default 'java',
    image_path text not null default './java.jpg',
    problem_html text not null,
    code_text text not null,
    average_time_label text not null default '0.134 s',
    average_time_ms text not null default '134.30 ms',
    maximum_time_label text not null default '0.142 s',
    maximum_time_ms text not null default '142.00 ms',
    shown_result text not null default '2 out of 2 shown test case(s) passed',
    hidden_result text not null default '2 out of 2 hidden test case(s) passed',
    sort_order integer not null default 1,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.programs
add column if not exists image_path text not null default './java.jpg';

create extension if not exists pg_trgm with schema extensions;

create index if not exists programs_title_trgm_idx
on public.programs
using gin (title gin_trgm_ops);

create index if not exists programs_slug_trgm_idx
on public.programs
using gin (slug gin_trgm_ops);

alter table public.programs enable row level security;

drop policy if exists "Programs are readable by everyone" on public.programs;
create policy "Programs are readable by everyone"
on public.programs
for select
using (is_active = true);

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms
) values (
    'generate-electricity-bill',
    'Generate Electricity Bill',
    'Electricit...',
    'java',
    './java.jpg',
    '<p>Create a Java program with a class named <strong>ElectricityBill</strong> that takes user input for the following details: <em>consumer number</em>, <em>consumer name</em>, <em>previous month reading</em>, <em>current month reading</em>, and <em>EBconnectiontype</em> (either "domestic" or "commercial"). Implement a method called calculateBillAmount() to compute the bill based on units consumed using a slab-based tariff system.</p>

<p>For domestic connections:</p>
<ul class="bullet-list">
    <li>First 100 units: Rs. 1 per unit.</li>
    <li>101-200 units: Rs. 2.50 per unit.</li>
    <li>201-500 units: Rs. 4 per unit.</li>
    <li>Above 500 units: Rs. 6 per unit.</li>
</ul>

<p>For commercial connections:</p>
<ul class="bullet-list">
    <li>First 100 units: Rs. 2 per unit.</li>
    <li>101-200 units: Rs. 4.50 per unit.</li>
    <li>201-500 units: Rs. 6 per unit.</li>
    <li>Above 500 units: Rs. 7 per unit.</li>
</ul>

<p><strong>Input Format:</strong></p>
<ul class="bullet-list">
    <li>The program should accept the following inputs in order:</li>
</ul>

<div class="sample-card format-card">
    <span>Consumer Number (integer)<br>Consumer Name (String)<br>Previous Month Reading (integer)<br>Current Month Reading (integer)<br>EB Connection Type (String - "domestic" or "commercial")</span>
</div>

<p><strong>Output Format:</strong></p>
<ul class="bullet-list">
    <li>The program should display the bill information in the following format:</li>
</ul>

<div class="sample-card format-card">
    <span>Electricity Bill Details:<br>Consumer Number: [consumerNo]<br>Consumer Name: [consumerName]<br>Previous Month Reading: [previousMonthReading]<br>Current Month Reading: [currentMonthReading]<br>EB Connection Type: [ebConnectionType]<br>Bill Amount: Rs. [calculatedBillAmount]</span>
</div>

<p><strong>Note:</strong></p>
<ul class="bullet-list note-list">
    <li>Ensure the program validates that the current reading is not less than the previous reading.</li>
    <li>The connection type should be case-insensitive (accept "Domestic", "DOMESTIC", etc.)</li>
    <li>Display the bill amount with 2 decimal places for better readability.</li>
</ul>',
    'import java.util.Scanner;
public class ElectricityBill {

    private int consumerNo;
    private String consumerName;
    private int previousMonthReading;
    private int currentMonthReading;
    private String ebConnectionType;
    public ElectricityBill(int consumerNo, String consumerName, int previousMonthReading, int currentMonthReading, String ebConnectionType) {

        this.consumerNo = consumerNo;
        this.consumerName = consumerName;
        this.previousMonthReading = previousMonthReading;
        this.currentMonthReading = currentMonthReading;
        this.ebConnectionType = ebConnectionType;
    }
    public double calculateBillAmount() {

        int unitsConsumed = currentMonthReading - previousMonthReading;
        double billAmount = 0.0;
        if (ebConnectionType.equalsIgnoreCase("Domestic")) {
            if (unitsConsumed <= 100) {
                billAmount = unitsConsumed * 1.0;
            } else if (unitsConsumed <= 200) {
                billAmount = (100 * 1.0) + ((unitsConsumed - 100) * 2.5);

            } else if (unitsConsumed <= 500) {
                billAmount = (100 * 1.0) + (100 * 2.5) + ((unitsConsumed - 200) * 4.0);
            } else {
                billAmount = (100 * 1.0) + (100 * 2.5) + (300 * 4.0) + ((unitsConsumed - 500) * 6.0);
            }
        } else if

(ebConnectionType.equalsIgnoreCase("Commercial")) {
            if (unitsConsumed <= 100) {
                billAmount = unitsConsumed * 2.0;
            } else if (unitsConsumed <= 200) {
                billAmount = (100 * 2.0) + ((unitsConsumed - 100) * 4.5);
            } else if (unitsConsumed <= 500) {
                billAmount = (100 * 2.0) + (100 * 4.5) + ((unitsConsumed - 200) * 6.0);
            } else {
                billAmount = (100 * 2.0) + (100 * 4.5) + (300 * 6.0) + ((unitsConsumed - 500) * 7.0);
            }
        }
        return billAmount;
    }



    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);

        System.out.print("Consumer Number: ");
        int consumerNo = input.nextInt();
        input.nextLine();

        System.out.print("Consumer Name: ");
        String consumerName = input.nextLine();

        System.out.print("Previous Month Reading: ");
        int previousMonthReading = input.nextInt();

        System.out.print("Current Month Reading: ");
        int currentMonthReading = input.nextInt();
        input.nextLine();

        System.out.print("Domestic/Commercial: ");
        String ebConnectionType = input.nextLine();

        // Creating ElectricityBill object with user-input data
        ElectricityBill bill = new ElectricityBill(consumerNo, consumerName, previousMonthReading,
currentMonthReading, ebConnectionType);

        // Calculating and displaying the bill amount
        double billAmount = bill.calculateBillAmount();
        System.out.println("Electricity Bill Details:");
        System.out.println("Consumer Number: " + consumerNo);
        System.out.println("Consumer Name: " + consumerName);
        System.out.println("Previous Month Reading: " + previousMonthReading);
        System.out.println("Current Month Reading: " + currentMonthReading);
        System.out.println("EB Connection Type: " + ebConnectionType);
        System.out.println("Bill Amount: Rs. " + billAmount);

        input.close();
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms'
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'finding-kth-smallest-element-in-array',
    'Finding kth Smallest Element in an Array',
    'KthSmall...',
    'java',
    './java.jpg',
    '<p>Write a Java program that takes an unsorted array of <em>n</em> integers and an integer <em>k</em> from the user and finds the <em>k<sup>th</sup></em> smallest element in the array. The array can not contain duplicate elements.</p>

<p><strong>Input Format:</strong></p>
<ul class="bullet-list">
    <li>The first line is an integer <em>n</em>, representing the number of elements in the array.</li>
    <li>The second line contains <em>n</em> integers separated by spaces, representing the elements of the array.</li>
    <li>The third line is an integer <em>k</em> representing the position (1-based index) of the element you need to find after sorting the array.</li>
</ul>

<p><strong>Output Format:</strong></p>
<ul class="bullet-list">
    <li>The output is the integer that represents the <em>k<sup>th</sup></em> smallest element of the array.</li>
</ul>

<p><strong>Note:</strong></p>
<ul class="bullet-list note-list">
    <li>The array elements must be unique.</li>
    <li>The value of <em>k</em> should be a valid index within the array bounds (i.e., 1 &le; <em>k</em> &le; array length). If <em>k</em> is out of bounds, print "Invalid input".</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q42211;
import java.util.Arrays;
import java.util.Scanner;

public class KthSmallest {


    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int n = scanner.nextInt();
        int[] array = new int[n];
        for (int i = 0; i < n; i++) {
            array[i] = scanner.nextInt();
        }
        int k = scanner.nextInt();
        Arrays.sort(array);
        if (k < 1 || k > n) {
            System.out.println("Invalid input");
        } else {
            System.out.println(array[k - 1]);
        }

        scanner.close();
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    2
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'matrix-addition',
    'Matrix Addition',
    'MatrixAd...',
    'java',
    './java.jpg',
    '<p>Write a Java program to add two matrices of size <em>n</em> &times; <em>n</em>. The program should print the resulting matrix after addition.</p>

<p><strong>Input Format:</strong></p>
<ul class="bullet-list">
    <li>The first line represents an integer <em>n</em>, which is the size of the square matrix.</li>
    <li>The next <em>n</em> lines contain <em>n</em> space-separated integers, representing the elements of the first matrix.</li>
    <li>The next <em>n</em> lines contain <em>n</em> space-separated integers, representing the elements of the second matrix.</li>
</ul>

<p><strong>Output Format:</strong></p>
<ul class="bullet-list">
    <li>Print the resultant matrix after addition, with each row on a new line and elements separated by a space.</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q42213;
import java.util.Scanner;

public class MatrixAddition {
    public static void main(String[] args){
        Scanner s=new Scanner(System.in);
        int n=s.nextInt();
        int a1[][]=new int[n][n];
        int a2[][]=new int[n][n];
        for(int i=0;i<n;i++){
            for(int j=0;j<n;j++){
                a1[i][j]=s.nextInt();
            }
        }
        for(int i=0;i<n;i++){
            for(int j=0;j<n;j++){
                a2[i][j]=s.nextInt();
            }
        }
        int[][] r=new int[n][n];
        for(int i=0;i<n;i++){
            for(int j=0;j<n;j++){
                r[i][j]=a1[i][j]+a2[i][j];
            }
        }
        for(int i=0;i<n;i++){
            for(int j=0;j<n;j++){
                System.out.print(r[i][j]+" ");
            }
            System.out.println();
        }
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    3
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'sub-array-with-given-sum',
    'Sub Array with Given Sum',
    'Subarray...',
    'java',
    './java.jpg',
    '<p>Given an array of integers and a target sum, find a contiguous subarray whose elements add up to exactly the target sum. Print the start and end indices (0-based) of the subarray. If no such subarray exists, print "No subarray".</p>

<p><strong>Input Format:</strong></p>
<ul class="bullet-list">
    <li>The first line contains an integer <em>n</em> (1 &le; <em>n</em> &le; 10<sup>5</sup>), the size of the array.</li>
    <li>The second line contains <em>n</em> space-separated integers representing the array elements (-10<sup>4</sup> &le; <em>arr[i]</em> &le; 10<sup>4</sup>).</li>
    <li>The third line contains an integer <em>targetSum</em> (-10<sup>9</sup> &le; <em>targetSum</em> &le; 10<sup>9</sup>), the desired sum.</li>
</ul>

<p><strong>Output Format:</strong></p>
<ul class="bullet-list">
    <li>If found, print two space-separated integers representing the start and end indices (inclusive) of the first occurring subarray.</li>
    <li>If not found, print "No subarray" (without quotes).</li>
</ul>

<p><strong>Sample Input 1:</strong></p>
<div class="sample-card format-card">
    <span>6<br>1 4 20 3 10 5<br>33</span>
</div>

<p><strong>Sample Output 1:</strong></p>
<div class="sample-card format-card">
    <span>2 4</span>
</div>

<p><strong>Explanation:</strong></p>
<ul class="bullet-list">
    <li>The subarray [20, 3, 10] sums to 33 (indices 2 to 4).</li>
</ul>

<p><strong>Sample Input 2:</strong></p>
<div class="sample-card format-card">
    <span>4<br>10 20 30 40<br>100</span>
</div>

<p><strong>Sample Output 2:</strong></p>
<div class="sample-card format-card">
    <span>No subarray</span>
</div>

<p><strong>Explanation:</strong></p>
<ul class="bullet-list">
    <li>No contiguous subarray sums to 100.</li>
</ul>

<p><strong>Constraints:</strong></p>
<ul class="bullet-list">
    <li>The solution must have <em>O(n)</em> time complexity.</li>
    <li>The solution must use <em>O(1)</em> extra space (apart from the input array).</li>
</ul>

<p><strong>Note:</strong></p>
<ul class="bullet-list note-list">
    <li>Only the first valid subarray should be returned if multiple exist.</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q42212;
import java.util.Scanner;

public class SubarraywithSum {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int n = scanner.nextInt();
        int[] array = new int[n];
        for (int i = 0; i < n; i++) {
            array[i] = scanner.nextInt();
        }
        int targetSum = scanner.nextInt();
        int currentSum = 0;
        int start = 0;
        for (int end = 0; end < n; end++) {
            currentSum += array[end];
            while (currentSum > targetSum && start <= end) {
                currentSum -= array[start];
                start++;
            }
            if (currentSum == targetSum) {
                System.out.println(start + " " + end);
                scanner.close();
                return;
            }
        }
        System.out.println("No subarray");
        scanner.close();
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    4
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'matrix-subtraction',
    'Matrix Subtraction',
    'Matrix Su...',
    'java',
    './java.jpg',
    '<p>Write a Java program to subtract two square matrices of size <em>n</em> &times; <em>n</em>. The program should print the resulting matrix after subtraction.</p>

<p><strong>Input Format:</strong></p>
<ul class="bullet-list">
    <li>The first integer represents the size <em>n</em> of the square matrices.</li>
    <li>The next <em>n</em> &times; <em>n</em> integers represent the elements of the first matrix.</li>
    <li>The next <em>n</em> &times; <em>n</em> integers represent the elements of the second matrix.</li>
</ul>

<p><strong>Output Format:</strong></p>
<ul class="bullet-list">
    <li>The resulting matrix after subtraction is printed in matrix form.</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q42214;
import java.util.Scanner;

public class MatrixSubtraction {
    public static void main(String[] args){
        Scanner s=new Scanner(System.in);
        int n=s.nextInt();
        int[][] a1=new int[n][n];
        int[][] a2=new int[n][n];
        for(int i=0;i<n;i++){
            for(int j=0;j<n;j++){
                a1[i][j]=s.nextInt();
            }
        }
        for(int i=0;i<n;i++){
            for(int j=0;j<n;j++){
                a2[i][j]=s.nextInt();
            }
        }
        int[][] r=new int[n][n];
        for(int i=0;i<n;i++){
            for(int j=0;j<n;j++){
                r[i][j]=a1[i][j]-a2[i][j];
            }
        }
        for(int i=0;i<n;i++){
            for(int j=0;j<n;j++){
                System.out.print(r[i][j]+" ");
            }
            System.out.println();
        }
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    5
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'program-to-find-multiplication-of-two-matrices',
    'Program to find Multiplication of Two matrices',
    'Multiplica...',
    'java',
    './java.jpg',
    '<p>Write a class <code>MultiplicationOfMatrix</code> with a public method <code>multiplication</code> which returns the multiplication result of its arguments. If the first argument column size is not equal to the row size of the second argument, then the method should return null.</p>

<p>Consider the following example for your understanding</p>

<div class="sample-card format-card">
    <span>Matrix 1:<br>Enter number of rows: 3<br>Enter number of columns: 2<br>Enter 2 numbers separated by space<br>Enter row 1: 1 2<br>Enter row 2: 4 5<br>Enter row 3: 7 8<br>Matrix 2:<br>Enter number of rows: 2<br>Enter number of columns: 3<br>Enter 3 numbers separated by space<br>Enter row 1: 1 2 3<br>Enter row 2: 4 5 6<br>Multiplication of the two given matrices is:<br>9 12 15<br>24 33 42<br>39 54 69</span>
</div>

<div class="sample-card format-card">
    <span>Matrix 1:<br>Enter number of rows: 2<br>Enter number of columns: 2<br>Enter 2 numbers separated by space<br>Enter row 1: 1 2<br>Enter row 2: 3 4<br>Matrix 2:<br>Enter number of rows: 3<br>Enter number of columns: 2<br>Enter 2 numbers separated by space<br>Enter row 1: 1 2<br>Enter row 2: 4 5<br>Enter row 3: 2 3<br>Multiplication of matrices is not possible</span>
</div>

<p><strong>Note:</strong> Please don''t change the package name.</p>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q11106;
public class MultiplicationOfMatrix{
    public int[][] multiplication(int[][] matrix1, int[][] matrix2) {
        if (matrix1[0].length != matrix2.length) {
            return null;
        }

        int rows1 = matrix1.length;
        int cols1 = matrix1[0].length;
        int rows2 = matrix2.length;
        int cols2 = matrix2[0].length;
        int[][] result = new int[rows1][cols2];
        for (int i = 0; i < rows1; i++) {
            for (int j = 0; j < cols2; j++) {
                result[i][j] = 0;
                for (int k = 0; k < cols1; k++) {
                    result[i][j] += matrix1[i][k] * matrix2[k][j];
                }
            }
        }
        return result;
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    6
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'duplicates-in-array',
    'Duplicates in Array',
    'Duplicate...',
    'java',
    './java.jpg',
    '<p>Write a Java program that reads an array of integers from the user and removes any duplicate elements, keeping only the first occurrence of each element. The program should then print the array after duplicates have been removed.</p>

<p><strong>Input Format:</strong></p>
<ul class="bullet-list">
    <li>First line reads an integer, <em>n</em> representing the number of elements in the array.</li>
    <li>Second line reads <em>n</em> space separated integers as elements of the array.</li>
</ul>

<p><strong>Output Format:</strong></p>
<ul class="bullet-list">
    <li>Print the resulting array with a print message:</li>
</ul>

<div class="sample-card format-card">
    <span>Array after removing duplicates:<br>&lt;intValue1&gt; &lt;intValue2&gt; &lt;intValue3&gt;...</span>
</div>

<p><strong>Note:</strong></p>
<ul class="bullet-list note-list">
    <li>Refer to the visible test cases to strictly match the input/output format.</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q42499;
import java.util.Scanner;

public class Duplicates {
    public static void main(String[] args){
        Scanner s=new Scanner(System.in);
        int n=s.nextInt();
        int[] a=new int[n];
        for(int i=0;i<n;i++){
            a[i]=s.nextInt();
        }
        for(int i=0;i<n;i++){
            for(int j=i+1;j<n;j++){
                if(a[i]==a[j]){
                    for(int k=j;k<n-1;k++){
                        a[k]=a[k+1];
                    }
                    n--;
                    j--;
                }
            }
        }

        System.out.println("Array after removing duplicates:");
        for(int i=0;i<n;i++){
            System.out.print(a[i]+" ");
        }
        System.out.println();
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    7
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'generic-adt-using-interface',
    'Generic ADT using Interface',
    'StackADT...',
    'java',
    './java.jpg',
    '<p>Design Interface for ADT Stack. Implement this interface using array. Provide necessary exception handling in both implementation.</p>

<p><strong>Note:</strong> The main function is provided to you in the editor.</p>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q42111;
import java.io.*;

class Stack_array {
    private int maxSize = 100;
    private int[] stack;
    private int top;
    public Stack_array() {
        stack = new int[maxSize];
        top = -1;
    }
    public void push() throws IOException {
        if (top == maxSize - 1) {
            System.out.println("Stack Overflow");
            return;
        }
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        System.out.print("Enter the element");
        int element = Integer.parseInt(br.readLine());
        stack[++top] = element;
    }
    public void pop() {
        if (top == -1) {
            System.out.println("Stack Underflow");
            return;
        }
        System.out.println("Popped element: " + stack[top--]);
    }
    public void display() {
        if (top == -1) {
            System.out.println("Stack is empty");
            return;
        }
        System.out.print("Elements are:  ");
        for (int i = 0; i <= top; i++) {
            if (i == top) {
                System.out.print(stack[i] + " <---"); // No space after the last arrow
            } else {
                System.out.print(stack[i] + " <--- ");
            }
        }
        System.out.println();
    }
}

class StackADT {
    public static void main(String args[]) throws IOException {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        System.out.println("Implementation of Stack using Array");
        Stack_array stk = new Stack_array();
        int ch = 0;
        do {
            System.out.println("1.Push 2.Pop 3.Display 4.Exit");
            System.out.print("Enter your choice: ");
            ch = Integer.parseInt(br.readLine());
            switch (ch) {
                case 1:
                    stk.push();
                    break;
                case 2:
                    stk.pop();
                    break;
                case 3:
                    stk.display();
                    break;
                case 4:
                    System.exit(0);
            }
        } while (ch != 4);
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    8
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'area-of-shapes-using-abstract-classes',
    'Area of Shapes using Abstract classes',
    'Main...',
    'java',
    './java.jpg',
    '<p>Write a Java program that defines an abstract class <code>Shape</code> with two sub classes <code>Rectangle</code>, <code>Triangle</code>, <code>Circle</code>. Each subclass calculates and prints the area of the respective shape based on user-provided dimensions. Implement the program as described below:</p>

<p>Define an abstract class <code>Shape</code> with the following attributes and methods:<br>Variables:<br>- <code>dimension1</code> (double)<br>- <code>dimension2</code> (double)<br>Methods:<br>- <code>public abstract void printArea()</code>: an abstract method to calculate and print the area of the shape.</p>

<p>Implement three subclasses of <code>Shape</code>:<br>- <code>Rectangle</code>: Computes area using the formula <code>length * width</code>.<br>- <code>Triangle</code>: Computes area using the formula <code>0.5 * base * height</code>.<br>- <code>Circle</code>: Computes area using the formula <code>PI * Radius * Radius</code> (hint: Use Math.PI)</p>

<p><strong>Input and Output Format:</strong><br>1. Rectangle:<br>- The program first prompts the user with:<br><code>length and width of Rectangle:</code><br>- The user enters two double values representing the length and width of the rectangle.<br>- Immediately after reading the input, the program prints:<br><code>Area of Rectangle: &lt;area formatted to two decimal places&gt;</code></p>

<p>2. Triangle:<br>- Next, the program prompts the user with:<br><code>base and height of Triangle:</code><br>- The user enters two double values representing the base and height of the triangle.<br>- Immediately after reading the input, the program prints:<br><code>Area of Triangle: &lt;area formatted to two decimal places&gt;</code></p>

<p>3. Circle:<br>- Finally, the program prompts the user with:<br><code>Radius of Circle:</code><br>- The user enters one double value representing the radius of the circle.<br>- Immediately after reading the input, the program prints:<br><code>Area of Circle: &lt;area formatted to two decimal places&gt;</code></p>

<p><strong>Note:</strong><br>- Refer to the sample test cases for print statements to be ordered.</p>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q10803;
import java.util.Scanner;

abstract class Shape{
    public double dimension1;
    public double dimension2;
    
    public Shape(double dimension1, double dimension2) {
        this.dimension1 = dimension1;
        this.dimension2 = dimension2;
    }
    
    public abstract void printArea();
}

class Rectangle extends Shape{
    
    public Rectangle(double length, double width) {
        super(length, width);
    }
    
    @Override
    public void printArea() {
        double area = dimension1 * dimension2;
        System.out.printf("Area of Rectangle: %.2f\n", area);
    }
}

class Triangle extends Shape{
    
    
    public Triangle(double base, double height) {
        super(base, height);
    }
    
    @Override
    public void printArea() {
        double area = 0.5 * dimension1 * dimension2;
        System.out.printf("Area of Triangle: %.2f\n", area);
    }
// Type your content here
}


class Circle extends Shape{
    
    
    public Circle(double radius) {
        super(radius, 0); // dimension2 is not needed for circle
    }
    
    @Override
    public void printArea() {
        double area = Math.PI * dimension1 * dimension1;
        System.out.printf("Area of Circle: %.2f\n", area);
    }
}


public class Main {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        
        System.out.println("length and width of Rectangle: ");
        double length = scanner.nextDouble();
        double width = scanner.nextDouble();
        Rectangle rectangle = new Rectangle(length, width);
        rectangle.printArea();
        
        System.out.println("base and height of Triangle: ");
        double base = scanner.nextDouble();
        double height = scanner.nextDouble();
        Triangle triangle = new Triangle(base, height);
        triangle.printArea();
        
        System.out.println("Radius of Circle: ");
        double radius = scanner.nextDouble();
        Circle circle = new Circle(radius);
        circle.printArea();
        
        scanner.close();
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    9
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'square-root-checker',
    'Square root Checker',
    'UniqueCa...',
    'java',
    './java.jpg',
    '<p>Ram wants to create a unique calculator that prints the square root of the given number if the square root is an integer, otherwise, it will need to print <code>Square root is not an integer</code>. Ram wants to build this calculator by using user-defined exceptions in Java.</p>

<p>What will be the code that helps Ram to achieve this?</p>

<p><strong>Input Format:</strong></p>
<ul class="bullet-list">
    <li>The input line reads an integer whose square root needs to be printed.</li>
</ul>

<p><strong>Output Format:</strong></p>
<ul class="bullet-list">
    <li>The output is an integer if the square root of the given number is an integer, otherwise, it will print <code>Square root is not an integer</code> by using an exception.</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q28875;

import java.util.Scanner;

// User-defined exception
class NonIntegerSquareRootException extends Exception {
    public NonIntegerSquareRootException(String message) {
        super(message);
    }
}

public class UniqueCalculator {
    // write your code here
    
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int number = scanner.nextInt();
        
        
        
        
        
        try {
            // write your code here
            
            int sqrt = (int) Math.sqrt(number);
            if (sqrt * sqrt == number) {
                System.out.println(sqrt);
            } else {
                throw new NonIntegerSquareRootException("Square root is not an integer");
            }
            
        } catch (   NonIntegerSquareRootException e    ) {
            // write your code here
            
            System.out.println(e.getMessage());
        }
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    10
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'producer-consumer-concept',
    'Producer Consumer Concept',
    'Producer...',
    'java',
    './java.jpg',
    '<p>Write a Java program using synchronized threads, which demonstrates producer consumer concept.</p>

<p>The Producer-Consumer problem is a classic synchronization problem in computer science. It involves two types of threads:</p>
<ul class="bullet-list">
    <li>Producer: This thread generates data (e.g., items) and places it in a shared resource (like a buffer)</li>
    <li>Consumer: This thread takes data (items) from the shared resource for processing or consumption.</li>
</ul>

<p>The problem revolves around coordinating these threads such that:</p>
<ul class="bullet-list">
    <li>The producer does not produce when the buffer is full.</li>
    <li>The consumer does not consume when the buffer is empty.</li>
    <li>Both threads operate safely without corrupting the shared resource.</li>
</ul>

<p>To achieve synchronization in Java, we can use the synchronized keyword along with wait and notify methods to control the interaction between the threads.</p>

<p><strong>Input Format:</strong></p>
<ul class="bullet-list">
    <li>Prompt the user to enter an integer representing the number of items to produce along with a print statement "Enter the number of items to produce: "</li>
</ul>

<p><strong>Output Format:</strong></p>
<p>Output should print the following:</p>
<ul class="bullet-list">
    <li>Messages indicating the production of each item as &lt;Produced: {Produced item}&gt;</li>
    <li>Messages indicating the consumption of each item as &lt;Consumed: {Consumed item}&gt;</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q28802;
import java.util.LinkedList;
import java.util.Scanner;
class Buffer {
    private final LinkedList<Integer> list = new LinkedList<>();
    private final int capacity = 1;

    public synchronized void produce(int item) throws InterruptedException {
        while (list.size() == capacity) {
            wait();
        }
        list.add(item);
        System.out.println("Produced: " + item);
        notify();
    }
    public synchronized int consume() throws InterruptedException {
        while (list.isEmpty()) {
            wait();
        }
        int item = list.removeFirst();
        System.out.println("Consumed: " + item);
        notify();
        return item;
    }
}
class Producer extends Thread {
    private final Buffer buffer;
    private final int itemsToProduce;

    public Producer(Buffer buffer, int itemsToProduce) {
        this.buffer = buffer;
        this.itemsToProduce = itemsToProduce;
    }
    @Override
    public void run() {
        try {
            for (int i = 1; i <= itemsToProduce; i++) {
                buffer.produce(i);
                Thread.sleep(100); // Simulate time taken to produce
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }
}
class Consumer extends Thread {
    private final Buffer buffer;
    private final int itemsToConsume;

    public Consumer(Buffer buffer, int itemsToConsume) {
        this.buffer = buffer;
        this.itemsToConsume = itemsToConsume;
    }

    @Override
    public void run() {
        try {
            for (int i = 1; i <= itemsToConsume; i++) {
                buffer.consume();
                Thread.sleep(150); // Simulate time taken to consume
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }
}

public class ProducerConsumerDemo {
    
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter the number of items to produce: ");
        int itemCount = scanner.nextInt();

        Buffer buffer = new Buffer();
        Producer producer = new Producer(buffer, itemCount);
        Consumer consumer = new Consumer(buffer, itemCount);

        producer.start();
        consumer.start();

        try {
            producer.join();
            consumer.join();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    11
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'reverse-the-words-and-count-the-letters-in-a-sentence',
    'Reverse the Words and Count the Letters in a Sentence',
    'ReverseA...',
    'java',
    './java.jpg',
    '<p>Write a Java program that takes a sentence as input and reverse the order of the words and count the frequency of each letter in the reversed string. The program should count the frequency of each letter (case-insensitive), ignoring non-alphabetic characters.</p>

<p><strong>Input Format:</strong></p>
<ul class="bullet-list">
    <li>The program should prompt the user to enter a string of words.</li>
</ul>

<p><strong>Output Format:</strong></p>
<ul class="bullet-list">
    <li>Display the reversed words.</li>
    <li>Display the frequency of each letter in the reversed string in lexicographical order.</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q42718;
import java.util.Scanner;

public class ReverseAndCount {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String input = scanner.nextLine();
        String reversed = reverseWords(input);
        System.out.println(reversed);
        countLetterFrequency(reversed);
        scanner.close();
    }

    private static String reverseWords(String str) {
        String[] words = str.split(" ");
        StringBuilder reversed = new StringBuilder();
        for (int i = words.length - 1; i >= 0; i--) {
            reversed.append(words[i]).append(" ");
        }
        return reversed.toString().trim();
    }

    private static void countLetterFrequency(String str) {
        int[] frequency = new int[26];
        for (char c : str.toLowerCase().toCharArray()) {
            if (Character.isLetter(c)) {
                frequency[c - ''a'']++;
            }
        }
        for (char i = ''a''; i <= ''z''; i++) {
            if (frequency[i - ''a''] > 0) {
                System.out.println(i + ": " + frequency[i - ''a'']);
            }
        }
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    12
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'number-of-patterns',
    'Number of Patterns',
    'PatternR...',
    'java',
    './java.jpg',
    '<p>Given a binary string, your task is to find the number of patterns of form 1[0]1, where [0] represents any number of consecutive zeroes (with at least one 0), and there should not be any other character except 0 in the [0] sequence. The pattern must start with a 1, followed by one or more zeroes, and end with a 1.</p>

<p>Write a Java program that will take a binary string as input and display the number of such patterns found.</p>

<p><strong>Input Format:</strong></p>
<ul class="bullet-list">
    <li>A line containing a binary string, where each character is either 0 or 1.</li>
</ul>

<p><strong>Output Format:</strong></p>
<ul class="bullet-list">
    <li>An integer representing the number of patterns of the form 1[0]1 found in the binary string.</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q42741;
import java.util.Scanner;

public class PatternRecognition {
    
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String binaryString = scanner.nextLine();
        int patternCount = countPatterns(binaryString);
        System.out.println(patternCount);
        scanner.close();
    }
    
    private static int countPatterns(String str) {
        int count = 0;
        boolean foundOne = false;
        int zeroCount = 0;
        for (char c : str.toCharArray()) {
            if (c == ''1'') {
                if (foundOne && zeroCount > 0) {
                    count++;
                }
                foundOne = true;
                zeroCount = 0;
            } else if (c == ''0'') {
                if (foundOne) {
                    zeroCount++;
                }
            }
        }
        return count;
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    13
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'remove-all-the-occurrences-of-the-substring-in-a-string',
    'Remove all the Occurrences of the Substring in a String',
    'RemoveOc...',
    'java',
    './java.jpg',
    '<p>Given two strings <em>S1</em> and <em>S2</em>, your task is to remove all occurrences of string <em>S2</em> in <em>S1</em> and print the remaining part of <em>S1</em>. If <em>S2</em> is not found in <em>S1</em>, the original string <em>S1</em> should be printed unchanged.</p>

<p>Write a Java program that will take two strings as input: <em>S1</em> (the main string) and <em>S2</em> (the substring to be removed). The program will output the modified string after removing all instances of <em>S2</em>.</p>

<p><strong>Input Format:</strong></p>
<ul class="bullet-list">
    <li>The first line contains a string <em>S1</em>, where <em>S1</em> consists of any characters.</li>
    <li>The second line contains a string <em>S2</em>, where <em>S2</em> consists of any characters.</li>
</ul>

<p><strong>Output Format:</strong></p>
<ul class="bullet-list">
    <li>A single line containing the modified version of string <em>S1</em>, with all occurrences of <em>S2</em> removed. If <em>S2</em> is not found in <em>S1</em>, print <em>S1</em> unchanged.</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q42742;
import java.util.Scanner;
public class RemoveOccurrences {
    
    public static String rem(String str, String substr) {
        return str.replace(substr, "");
    }
    
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String str = scanner.nextLine();
        String substr = scanner.nextLine();
        String result = rem(str, substr);
        System.out.println(result);
        scanner.close();
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    14
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'longest-repeating-sequence',
    'Longest Repeating Sequence',
    'LongestS...',
    'java',
    './java.jpg',
    '<p>Given a string <em>S</em>, your task is to find the longest repeating sequence of characters in the string. A repeating sequence is defined as a substring that appears more than once in the string. The program should return the longest such repeating sequence. If there are no repeating sequences, the program should display "No repeating sequence".</p>

<p>Write a Java program that takes a string <em>S</em> as input and outputs the longest repeating sequence of characters. If there is no repeating sequence, print a specific message.</p>

<p><strong>Input Format:</strong></p>
<ul class="bullet-list">
    <li>A single line containing a string <em>S</em>, consisting of lowercase or uppercase letters.</li>
</ul>

<p><strong>Output Format:</strong></p>
<ul class="bullet-list">
    <li>A single line containing the longest repeating sequence of characters in <em>S</em>.</li>
    <li>If there is no repeating sequence, print "No repeating sequence".</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q42743;
import java.util.Scanner;

public class LongestSequence {
    
    public static String longest(String str) {
        String longseq = "";
        int n = str.length();
        for (int i = 0; i < n; i++) {
            for (int j = i + 1; j < n; j++) {
                String lr = getlong(str.substring(i), str.substring(j));
                if (lr.length() > longseq.length()) {
                    longseq = lr;
                }
            }
        }
        return longseq.isEmpty() ? "No repeating sequence" : longseq;
    }
    
    private static String getlong(String s1, String s2) {
        int i = 0;
        while (i < s1.length() && i < s2.length() && s1.charAt(i) == s2.charAt(i)) {
            i++;
        }
        return s1.substring(0, i);
    }
    
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println(longest(scanner.nextLine()));
        scanner.close();
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    15
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'unique-string-values',
    'Unique String Values',
    'UniquePe...',
    'java',
    './java.jpg',
    '<p>Given a string <em>S</em> containing unique characters, your task is to calculate the number of distinct permutations that can be formed by rearranging the letters of the string.</p>

<p>Write a Java program that takes a string <em>S</em> as input and outputs the number of distinct permutations that can be formed.</p>

<p><strong>Input Format:</strong></p>
<ul class="bullet-list">
    <li>A single line containing a string <em>S</em>, where each character is unique (all distinct letters).</li>
</ul>

<p><strong>Output Format:</strong></p>
<ul class="bullet-list">
    <li>A single integer represents the number of distinct permutations that can be formed from the string <em>S</em>.</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q42744;
import java.util.Scanner;

public class UniquePermutations {
    private static int factorial(int n) {
        int fact = 1;
        for (int i = 2; i <= n; i++) {
            fact *= i;
        }
        return fact;
    }
    
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String input = scanner.nextLine();
        int length = input.length();
        int permutations = factorial(length);
        System.out.println(permutations);
        scanner.close();
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    16
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'string-operations-using-list',
    'String Operations using List',
    'StringOp...',
    'java',
    './java.jpg',
    '<p>Write a Java program that performs various string operations using an ArrayList. Implement the following functionalities:</p>
<ol>
    <li>Append: Add a string to the end of the list.</li>
    <li>Insert String at Index: Insert a string at a specified index in the list.</li>
    <li>Search String: Search for a string in the list and indicate whether it exists.</li>
    <li>List strings starting with Letter: List all strings from the list that start with a specified letter.</li>
    <li>Display Strings: Show all strings currently stored in the list.</li>
</ol>

<p>Menu:</p>
<div class="sample-card format-card">
    <span>1. Append String<br>2. Insert String at Index<br>3. Search String<br>4. List strings starting with Letter<br>5. Display Strings<br>6. Exit</span>
</div>

<p><strong>Choice 1: Append String</strong></p>
<ul class="bullet-list">
    <li>The program prompts the user to enter a string by displaying:</li>
</ul>
<div class="sample-card format-card">
    <span>String to append: </span>
</div>
<ul class="bullet-list">
    <li>It then adds the entered string to the end of the list.</li>
</ul>

<p><strong>Choice 2: Insert String at Index</strong></p>
<ul class="bullet-list">
    <li>The program prompts the user to enter a string by displaying:</li>
</ul>
<div class="sample-card format-card">
    <span>String to insert: </span>
</div>
<ul class="bullet-list">
    <li>It then prompts the user to enter an index by displaying:</li>
</ul>
<div class="sample-card format-card">
    <span>Index to insert: </span>
</div>
<ul class="bullet-list">
    <li>If the index is valid (between 0 and the current list size), the string is inserted at the specified position.</li>
    <li>If the index is invalid, it prints:</li>
</ul>
<div class="sample-card format-card">
    <span>Invalid Index</span>
</div>

<p><strong>Choice 3: Search String</strong></p>
<ul class="bullet-list">
    <li>The program prompts the user to enter a string by displaying:</li>
</ul>
<div class="sample-card format-card">
    <span>String to search: </span>
</div>
<ul class="bullet-list">
    <li>If the string exists in the list, it prints:</li>
</ul>
<div class="sample-card format-card">
    <span>''&lt;string&gt;'' found.</span>
</div>
<ul class="bullet-list">
    <li>Otherwise, it prints:</li>
</ul>
<div class="sample-card format-card">
    <span>''&lt;string&gt;'' not found.</span>
</div>

<p><strong>Choice 4: List strings starting with Letter</strong></p>
<ul class="bullet-list">
    <li>The program prompts the user to enter a letter by displaying:</li>
</ul>
<div class="sample-card format-card">
    <span>Letter: </span>
</div>
<ul class="bullet-list">
    <li>It then prints all strings in the list that start with the given letter.</li>
    <li>If no such strings are found, it prints:</li>
</ul>
<div class="sample-card format-card">
    <span>No strings found</span>
</div>

<p><strong>Choice 5: Display Strings</strong></p>
<ul class="bullet-list">
    <li>The program displays all strings currently stored in the list.</li>
    <li>If the list is empty, it prints:</li>
</ul>
<div class="sample-card format-card">
    <span>List is empty</span>
</div>

<p><strong>Choice 6: Exit</strong></p>
<ul class="bullet-list">
    <li>The program closes the scanner and terminates. No menu is displayed.</li>
</ul>

<p><strong>Note:</strong></p>
<ul class="bullet-list note-list">
    <li>The main method has been provided to you in the editor; you are required to fill in the remaining function bodies.</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q42745;
import java.util.ArrayList;
import java.util.Scanner;

public class StringOperations {
    
    // ArrayList to store strings
    private ArrayList<String> stringList;
    
    // Constructor to initialize the ArrayList
    public StringOperations() {
        stringList = new ArrayList<>();
    }
    
    public void appendString(String str) {
        stringList.add(str);
    }
    
    public void insertString(int index, String str) {
        if (index >= 0 && index <= stringList.size()) {
            stringList.add(index, str);
        } else {
            System.out.println("Invalid index");
        }
    }
    
    public void searchString(String str) {
        if (stringList.contains(str)) {
            System.out.println("''" + str + "'' found.");
        } else {
            System.out.println("''" + str + "'' not found.");
        }
    }
    
    public void listStringsStartingWith(char letter) {
        boolean found = false;
        for (String str : stringList) {
            if (str.charAt(0) == letter) {
                System.out.println(str);
                found = true;
            }
        }
        if (!found) {
            System.out.println("No strings found.");
        }
    }
    
    public void displayList() {
        if (stringList.isEmpty()) {
            System.out.println("List is empty");
        } else {
            System.out.println(stringList);
        }
    }
    
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        StringOperations operations = new StringOperations();
        
        while (true) {
            System.out.println("1. Append String");
            System.out.println("2. Insert String at Index");
            System.out.println("3. Search String");
            System.out.println("4. List strings starting with Letter");
            System.out.println("5. Display Strings");
            System.out.println("6. Exit");
            System.out.print("Enter choice: ");
            
            int choice = scanner.nextInt();
            scanner.nextLine(); // Consume newline
            
            switch (choice) {
                case 1:
                    System.out.print("String to append: ");
                    String strToAppend = scanner.nextLine();
                    operations.appendString(strToAppend);
                    break;
                case 2:
                    System.out.print("String to insert: ");
                    String strToInsert = scanner.nextLine();
                    System.out.print("Index to insert: ");
                    int indexToInsert = scanner.nextInt();
                    scanner.nextLine();
                    operations.insertString(indexToInsert, strToInsert);
                    break;
                case 3:
                    System.out.print("String to search: ");
                    String strToSearch = scanner.nextLine();
                    operations.searchString(strToSearch);
                    break;
                case 4:
                    System.out.print("Letter: ");
                    char letter = scanner.nextLine().charAt(0);
                    operations.listStringsStartingWith(letter);
                    break;
                case 5:
                    operations.displayList();
                    break;
                case 6:
                    scanner.close();
                    return;
                default:
                    System.out.println("Invalid choice");
            }
        }
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    17
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'frequency-of-words-17',
    'Frequency of Words',
    'WordFreq...',
    'java',
    './java.jpg',
    '<p>Write a Java program that finds the frequency of words in a given text using an ArrayList. The program should read input text from the user, split the text into individual words, and then count the occurrences of each word.</p>

<p>Requirements:<br>1. Split the text into words, treating punctuation and whitespace as delimiters.<br>2. Count the frequency of each word, making the count case-insensitive.<br>3. Display the word frequencies in the format: {word}: {frequency}.</p>

<p><strong>Input Format:</strong></p>
<ul class="bullet-list">
    <li>The program should prompt the user to enter a line of text.</li>
</ul>

<p><strong>Output Format:</strong></p>
<ul class="bullet-list">
    <li>The program should print the frequency of each word in the text.</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q42746;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

public class WordFrequency {
    
    // Method to find the frequency of words in the given text
    public static void findWordFrequency(String text) {
        // Split the text into words
        String[] words = text.split("\\W+"); // Split by non-word characters
        ArrayList<String> wordList = new ArrayList<>();
        Map<String, Integer> wordFrequency = new HashMap<>();
        for (String word : words) {
            if (!word.isEmpty()) {
                word = word.toLowerCase();
                wordList.add(word);
                wordFrequency.put(word, wordFrequency.getOrDefault(word, 0) + 1);
            }
        }
        for (String word : wordList) {
            if (wordFrequency.containsKey(word)) {
                System.out.println(word + ": " + wordFrequency.get(word));
                wordFrequency.remove(word);
            }
        }
    }
    
    public static void main(String[] args){
        Scanner s=new Scanner(System.in);
        String text=s.nextLine();
        findWordFrequency(text);
        s.close();
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    18
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'frequency-of-words-13',
    'Frequency of Words',
    'WordFreq...',
    'java',
    './java.jpg',
    '<p>You are tasked with creating a program to analyze the frequency of words in a text file. Your program should read the contents of the file, process the text, and determine the most frequently occurring word. If there are multiple words with the highest frequency, output the first one that appears in the text.</p>

<p><strong>Input Format:</strong></p>
<ul class="bullet-list">
    <li>The program will read the name of a text file from the standard input. The file will contain lines of text.</li>
</ul>

<p><strong>Processing:</strong></p>
<ul class="bullet-list">
    <li>Read the entire content of the file.</li>
    <li>Normalize the text by:</li>
    <li>Removing all non-alphabetic characters (i.e., punctuation and numbers) using the regular expression [^a-zA-Z].</li>
    <li>Converting all letters to lowercase.</li>
    <li>Split the text into words based on whitespace.</li>
    <li>Count the frequency of each word.</li>
    <li>Identify the word with the highest frequency. In case of a tie, choose the first word that reaches the maximum frequency.</li>
</ul>

<p><strong>Output Format:</strong></p>
<ul class="bullet-list">
    <li>Print the most frequent word followed by its frequency in the format: "&lt;word&gt; : &lt;frequency&gt;".</li>
</ul>

<p><strong>Error Handling:</strong></p>
<ul class="bullet-list">
    <li>If the file does not exist or cannot be read, print the message: "File does not exist".</li>
</ul>

<p><strong>Details:</strong></p>
<ul class="bullet-list">
    <li>To ensure correct word counting, you need to remove all non-alphabetic characters from each word using the regular expression [^a-zA-Z] and then convert the result to lowercase.</li>
    <li>This means any characters that are not letters (like punctuation or digits) should be excluded from the words considered in the frequency analysis.</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    '/*package q28246;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;

*/
package q28246;
import java.io.*;
import java.util.*;

public class WordFrequency {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String fileName = scanner.nextLine();
        try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
            Map<String, Integer> wordCount = new LinkedHashMap<>();
            String line;

            while ((line = reader.readLine()) != null) {
line = line.replaceAll("[^a-zA-Z]", " ").toLowerCase();
                String[] words = line.split("\\s+");

                // Count word frequency
                for (String word : words) {
                    if (!word.isEmpty()) {
                        wordCount.put(word, wordCount.getOrDefault(word,0) + 1);
                    }
                }
            }
            String mostFrequentWord = null;
            int maxFrequency = 0;

            for (Map.Entry<String, Integer> entry : wordCount.entrySet()) {
                if (entry.getValue() > maxFrequency) {
                    mostFrequentWord = entry.getKey();
                    maxFrequency = entry.getValue();
                }
            }
            if (mostFrequentWord != null) {
                System.out.println(mostFrequentWord + " : " + maxFrequency);
            }
        } catch (IOException e) {
            System.out.println("File does not exist");
        }
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    19
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();

insert into public.programs (
    slug,
    title,
    tab_label,
    language,
    image_path,
    problem_html,
    code_text,
    average_time_label,
    average_time_ms,
    maximum_time_label,
    maximum_time_ms,
    sort_order
) values (
    'aanyas-calculator',
    'Aanya''s Calculator',
    'DivisionC...',
    'java',
    './java.jpg',
    '<p>Aanya, a school student, recently learned about division in math class. She wants to create a program to perform division operations like a calculator. Seeking help, she approached her teacher, who warned her to be cautious when dividing by zero. Can you assist Aanya in designing the program and handling the specific exception pointed out by her teacher?</p>

<p><strong>Input format:</strong></p>
<ul class="bullet-list">
    <li>The first two lines of the input are the integers which represent the numerator and denominator respectively.</li>
</ul>

<p><strong>Output format:</strong></p>
<ul class="bullet-list">
    <li>The output is the double value that represents the result after performing the division operation. If the denominator is zero, the program should display "Error: Division by zero is not possible".</li>
</ul>

<div class="sample-card">
    <span>Sample Test Cases</span>
    <button type="button" aria-label="Expand sample test cases">+</button>
</div>',
    'package q28182;
import java.util.Scanner;
public class DivisionCalc {
    
    
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int numerator = sc.nextInt();
        int denominator = sc.nextInt();
        
        try {
            
            
            if (denominator == 0) {
                throw new ArithmeticException("Division by zero");
            }double result = (double) numerator / denominator;
            System.out.println(result);
            
        }catch (             ArithmeticException e          ) {
            System.out.println("Error: Division by zero is not possible");
        }
    }
}',
    '0.134 s',
    '134.30 ms',
    '0.142 s',
    '142.00 ms',
    20
) on conflict (slug) do update set
    title = excluded.title,
    tab_label = excluded.tab_label,
    language = excluded.language,
    image_path = excluded.image_path,
    problem_html = excluded.problem_html,
    code_text = excluded.code_text,
    average_time_label = excluded.average_time_label,
    average_time_ms = excluded.average_time_ms,
    maximum_time_label = excluded.maximum_time_label,
    maximum_time_ms = excluded.maximum_time_ms,
    sort_order = excluded.sort_order,
    updated_at = now();
